micronaut:
  server:
    context-path: /mvp-match
  application:
    name: "mvp-match"
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:9ZZ6bh0Ilom4XPYZbN2NOml3z9FMfmpgXwovR9fp6ryDIoHRM9EPHAB7iHsc0fb}"'
jackson:
  serialization:
    writeDatesAsTimestamps: false


mvp:
  database:
    jdbcUrl: "jdbc:postgresql://localhost:5432/mvp"
    driverClassName: "org.postgresql.Driver"
    username: "mvp"
    password: "mvp"
    maximumPoolSize: 5